### ISSUE TITLE
Setup API

### ISSUE THREAD

**Issue by SebastianPlace** [SebastianPlace/fitness-frontend#3]
NOTE: Move this to API repo when created.

Todos:
- [ ] Router with routines endpoint
- [ ] Hook up postgres
- [ ] Unit tests

Acceptance:
- [ ] I can make a request to `/requests` and get a set of results back from the database.
